### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by idkjs**
add omf install instructions

### CODE REVIEW

**Comment by gazorby** [comment]
For now, only fisher is supported. I don't use oh-my-fish but if you are interested, PR is welcome!

**Comment by idkjs** [comment]
I am probably missing something but it seems to work just like in the instruction I provided so figured I would share it. If not, lets close it.

**Comment by gazorby** [comment]
I juste tried it on a fresh Linux user with omf, but the although the plugin was successfully installed, it dosn't show any tips. Were you able to make it work?

**Comment by idkjs** [comment]
I just uninstalled and reinstalled with the suggested command and it stopped working on uninstall, the worked on install in a fresh terminal.

Screen Shot 2020-10-31 at 11 18 14 AM

**Comment by gazorby** [comment]
Hi @idkjs, since we use fisher events to initialize abbreviations the first time, this plugin is definitely not compatible with omf. However, if you really want it to work, calling the `__abbr_tips_install` function right after the plugin installation should be enough.

Keep in mind that you will also have to clear plugin variables using `__abbr_tips_uninstall` when uninstalling.

**Pull request closed without merging**
